### ISSUE TITLE
梳理发现的一些问题

### ISSUE THREAD

**Issue by czy88840616** [midwayjs/midway-faas#115]
## 问题

- [x] 1、默认脚手架， f test 报错（输出http不对）

## 需求

- [x] 1、无触发器发布

**Comment by bear-ei** [comment]
问题：

1. 使用脚手架 f invoke -f index  选择阿里云fc运行函数后，在执行单元测试 npm test 就可以再次复现 #107 的问题。  

并且test的结果也会变成

```
{
  "headers": {
    "Content-Type": ["application/json; charset=utf-8"],
    "content-type": "text/plain"
  },
  "statusCode": 200,
  "body": "hello world",
  "base64Encoded": false
}
```

**Comment by czy88840616** [comment]
对，这个是因为变成了 http 触发器，返回的数据不同了。#107 的错误似乎是因为缓存的问题。

**Comment by bear-ei** [comment]
这里在放两个我在实际使用中比较希望有的两个需求。

需求：
 1.  invoke可以直接传递event，当前业务场景基本不用http触发器，都是使用event完成业务。 比如网关调用，oss事件触发等。

 2. 可以配置控制台环境变量 , 当前发布会把控制台上的环境变量重置。
