### ISSUE TITLE
configuration 业务自定义配置默认值无效 

### ISSUE THREAD

**Issue by bear-ei** [midwayjs/midway-faas#124]
```
@Configuration({
  importConfigs: [
    './config/config.default',
    './config/config.local',
    './config/config.prod',
  ],
})
```
Configuration 部署后没有配置环境变量的情况应该是默认加载 config.prod ？

当前实际情况是必须配置一个环境变量才能生效。

**Comment by czy88840616** [comment]
默认是 config.default + config.prod（默认拿到的应该是 prod) 。

**Comment by bear-ei** [comment]
是的，我是这样理解的默认  config.default + config.prod ，但是实际上如果不在控制台配置环境变量。 这个默认是不起效果的。 在初始化函数的时候获取不到任何配置。

**Comment by czy88840616** [comment]
我测试一下。

----

`default.ts` 会读，`prod` 似乎不会。

----

发现问题了。。。默认是 production。。。会去读 config.production.ts...
