### ISSUE TITLE
NAS 配置 deploy 的时候未生效，官方能提供一个教程吗？

### ISSUE THREAD

**Issue by tsui66** [midwayjs/midway-faas#183]
Node.js             v12.13.0
@midwayjs/faas-cli  v0.3.4

![image](https://user-images.githubusercontent.com/2019808/85918135-9bfce680-b892-11ea-8a6b-aee963543bd5.png)

**Comment by tsui66** [comment]
配置错误。

**Comment by czy88840616** [comment]
发布应该是可以的，同步的话后面会复用这个教程 https://help.aliyun.com/document_detail/147089.html
