### ISSUE TITLE
当前版本是否可以投入生产

### ISSUE THREAD

**Issue by bear-ei** [midwayjs/midway-faas#79]
请问当前版本是否有足够的稳定性可以投入生产使用。

**Comment by czy88840616** [comment]
当前框架基本稳定，主要在工具链层面做迭代，建议再等等，到 1.0 比较放心。现在发 1.0 的主要依赖有两个，一个是 @midwayjs/core 的 2.0 ，第二个是工具链的完善度。

**Comment by ZQun** [comment]
@czy88840616 这月能发？😊 要等[Egg3.0](https://github.com/eggjs/egg/issues/3644)吗

**Comment by czy88840616** [comment]
不等了，那边完全没动静。。

**Comment by bear-ei** [comment]
> 当前框架基本稳定，主要在工具链轴向完成，建议再等等，到1.0比较放心。现在发1.0的主要依赖有两个，一个是@ midwayjs / core的2.0，第二个是工具链的完善度。

好的，谢谢。

**Comment by waitingsong** [comment]
> 
> 
> 不等了，那边完全没动静。。

等egg3.0出来了，midway可以跟着出个 3.0，正好大版本一致。

**Comment by czy88840616** [comment]
@waitingsong 那升级太快了。。后面会慢慢把egg的依赖从强依赖变成弱依赖，会变成可替换的 web 层。
