### ISSUE TITLE
funSpec.events is not iterable

### ISSUE THREAD

**Issue by bear-ei** [midwayjs/midway-faas#80]
functions:
  rds:
    handler: rds.handler
    events:
      - http:
          method: get

我使用阿里云 api网关作为触发器的方式运行函数计算，http触发器不能和api网关同时存在。 当我在部署的过程中去掉events配置，会收到 funSpec.events is not iterable 错误。 请问有什么方法可以在部署的时候不配置触发器,否则每次部署完成我需要在控制台手动删除http触发器。

相关文档没有找到说明。

**Comment by czy88840616** [comment]
不配置触发器这个我们倒是没考虑。。我们调整一下
