### ISSUE TITLE
安装过程需要88s，优化

### ISSUE THREAD

**Issue by stone-jin** [midwayjs/midway-faas#84]
npm i -g @midwayjs/faas-cli --registry=https://registry.npm.taobao.org

耗费88s
```
+ @midwayjs/faas-cli@0.2.49
added 1556 packages from 1496 contributors in 88.201s
```

**Comment by waitingsong** [comment]
```sh
time npm i -g @midwayjs/faas-cli --registry=https://registry.npm.taobao.org --loglevel info

added 1541 packages from 1486 contributors in 81.05s

real    1m25.524s
user    0m0.015s
sys     0m0.182s
```

是比较慢（先执行了一次，中途退出，有部分的本地cache）

**Comment by echosoar** [comment]
![image](https://user-images.githubusercontent.com/14832743/79100215-923a0b80-7d98-11ea-8b55-9874ad38af78.png)


可以看出来最大的依赖是：@alicloud/fun、midway-bin(egg-bin)，把这两个移除掉依赖就会少很多

**Comment by echosoar** [comment]
use taobao npm
```
npm i -g @midwayjs/faas-cli --registry=https://registry.npm.taobao.org
```

#### @midwayjs/faas-cli@0.2.88
added 1709 packages from 1555 contributors in 81.183s
394M    node_modules

#### @midwayjs/faas-cli@0.2.90
> remove `midway-bin`

added 875 packages from 1039 contributors in 51.884s （-37%）
238M    node_modules （-40%）
